// © Copyright IBM Corp. 2023, 2024
// Copyright (c) 2020 Boomi, Inc.
package com.boomi.connector.databaseconnector.util;

import static com.boomi.connector.databaseconnector.util.DatabaseConnectorConstants.*;

import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Time;
import java.sql.Types;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import org.apache.commons.text.StringEscapeUtils;
import org.json.JSONObject;
import org.postgresql.util.PGobject;

import com.boomi.connector.api.ObjectData;
import com.boomi.util.IOUtil;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import oracle.jdbc.OracleType;
import oracle.sql.json.OracleJsonFactory;
import oracle.sql.json.OracleJsonObject;

/**
 * The Class QueryBuilderUtil.
 *
 * @author swastik.vn
 */
public class QueryBuilderUtil {

	/**
	 * Instantiates a new query builder util.
	 */
	private QueryBuilderUtil() {

	}

	/**
	 * Utility method to build the Query for procedure call.
	 *
	 * @param params     the params
	 * @param objectType the object type
	 * @return the string builder
	 */
	public static StringBuilder buildProcedureQuery(List<String> params, String objectType) {
		StringBuilder query = new StringBuilder("call ").append(objectType).append("(");
		if (!params.isEmpty()) {
			for (int i = 1; i <= params.size(); i++) {

				query.append("?");
				query.append(",");
			}
			query.deleteCharAt(query.length() - 1);
		}
		query.append(")");

		return query;

	}

	/**
	 * This Method will build the Procedure query for Microsoft SQL database.
	 *
	 * @param params   the params
	 * @param objectId the object id
	 * @return the string builder
	 */
	public static StringBuilder buildInitialQuerySqlDB(List<String> params, String objectId) {
		StringBuilder query = new StringBuilder();
		query.append("{call ").append(objectId);
		if (!params.isEmpty()) {
			query.append("(");
			for (int i = 0; i <= params.size() - 1; i++) {
				query.append(" ");
				query.append("?,");
			}
			query.deleteCharAt(query.length() - 1);
			query.append(")");
		}

		query.append("};");
		return query;

	}

	/**
	 * This method will build the initial characters required for the insert query.
	 *
	 * @param con          the con
	 * @param objectTypeId the object type id
	 * @return query
	 * @throws SQLException the SQL exception
	 */
	public static StringBuilder buildInitialQuery(Connection con, String objectTypeId) throws SQLException {
		StringBuilder query = new StringBuilder(QUERY_INITIAL + objectTypeId + "(");
		DatabaseMetaData md = con.getMetaData();
		try (ResultSet resultSet = md.getColumns(null, null, objectTypeId, null);) {
			while (resultSet.next()) {
				query.append(resultSet.getString(COLUMN_NAME));
				query.append(",");
			}
		}
		query.deleteCharAt(query.length() - 1);
		query.append(QUERY_VALUES);
		return query;

	}

	/**
	 * Builds the Insert Query Required of Prepared Statement in Dynamic Insert.
	 *
	 * @param con          the con
	 * @param objdata      the tracked data
	 * @param objectTypeId the object type id
	 * @param response
	 * @return the string builder
	 * @throws SQLException the SQL exception
	 * @throws IOException  Signals that an I/O exception has occurred.
	 */
	public static StringBuilder buildInitialInsertQuery(Connection con, ObjectData objdata, String objectTypeId)
			throws SQLException, IOException {
		StringBuilder query = new StringBuilder(QUERY_INITIAL + objectTypeId + "(");
		DatabaseMetaData md = con.getMetaData();
		int paramCount = 0;
		String autoIncrementColumn = getAutogeneratedKeys(con, objdata, objectTypeId);
		InputStream is = objdata.getData();
		ObjectMapper mapper = new ObjectMapper().disable(MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS)
				.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
		JsonNode node = mapper.readTree(is);
		try (ResultSet resultSet = md.getColumns(null, null, objectTypeId, null);) {
			while (resultSet.next()) {
				if (autoIncrementColumn == null || node.get(autoIncrementColumn) != null
						|| !autoIncrementColumn.equalsIgnoreCase(resultSet.getString(COLUMN_NAME))) {
					paramCount++;
					query.append(resultSet.getString(COLUMN_NAME));
					query.append(",");
				}
			}
		} finally {
			IOUtil.closeQuietly(is);
		}
		query.deleteCharAt(query.length() - 1);
		query.append(QUERY_VALUES);
		for (int i = 1; i <= paramCount; i++) {
			query.append("?");
			query.append(",");
		}
		query.deleteCharAt(query.length() - 1);
		query.append(")");
		return query;

	}

	/**
	 * Gets the autogenerated keys.
	 *
	 * @param connection   the connection
	 * @param objdata      the tracked data
	 * @param objectTypeId the object type id
	 * @return the autogenerated keys
	 * @throws SQLException the SQL exception
	 * @throws IOException  Signals that an I/O exception has occurred.
	 */
	public static String getAutogeneratedKeys(Connection connection, ObjectData objdata, String objectTypeId)
			throws SQLException, IOException {
		StringBuilder selectCommand = new StringBuilder("Select * from ");
		selectCommand.append(objectTypeId);
		JsonNode json = null;
		ObjectMapper mapper = new ObjectMapper().disable(MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS)
				.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
		String autoIncrementColumn = null;
		try (InputStream is = objdata.getData()) {
			json = mapper.readTree(is);
			try (PreparedStatement statement = connection.prepareStatement(selectCommand.toString());
					ResultSet resultSet = statement.executeQuery();) {
				ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
				for (int i = 1; i <= resultSetMetaData.getColumnCount(); i++) {
					if (resultSetMetaData.isAutoIncrement(i)) {
						if (json.get(resultSetMetaData.getColumnName(i)) != null) {
							autoIncrementColumn = null;
						} else {
							autoIncrementColumn = resultSetMetaData.getColumnName(i);
						}
					}
				}
			}
		}
		return autoIncrementColumn;
	}

	/**
	 * Validate the table name.
	 *
	 * @param finalQuery the final query
	 * @return the string
	 * @throws IndexOutOfBoundsException the index out of bounds exception
	 */
	public static String validateTheTableName(String finalQuery) {
		int findIndex = finalQuery.lastIndexOf("FROM");
		String tep = finalQuery.substring(findIndex);
		if (tep.indexOf(" ") >= 0) {
			tep = tep.substring(tep.indexOf(" ") + 1);
			if (tep.indexOf(" ") >= 0)
				finalQuery = tep.substring(0, tep.indexOf(" "));
			else
				finalQuery = tep;
		}
		if (finalQuery.contains(".")) {
			finalQuery = finalQuery.substring(finalQuery.indexOf(".") + 1, finalQuery.length());
		}
		return finalQuery;
	}

	/**
	 * Checks the column data type and adds the parameter to the prepared statement.
	 *
	 * @param dataTypes the data types
	 * @param key       the key
	 * @param value     the value
	 * @param bstmnt    the query
	 * @param i         the i
	 * @param con       the con
	 * @throws SQLException the SQL exception
	 */
	public static void checkDataType(Map<String, String> dataTypes, String key, String value, PreparedStatement bstmnt,
			int i, Connection con) throws SQLException {
		String databaseName = con.getMetaData().getDatabaseProductName();
		switch (dataTypes.get(key)) {
		case INTEGER:
			if (value != null) {
				int num = Integer.parseInt(value);
				bstmnt.setInt(i, num);
			} else {
				bstmnt.setNull(i, Types.INTEGER);
			}
			break;
		case DATE:
			if (value != null) {
				if ("Oracle".equals(databaseName)) {
					bstmnt.setString(i, value);
				} else {
					bstmnt.setDate(i, Date.valueOf(value));
				}
			} else {
				bstmnt.setNull(i, Types.DATE);
			}
			break;
		case STRING:
			if (value != null) {
				bstmnt.setString(i, value);
			} else {
				bstmnt.setNull(i, Types.VARCHAR);
			}
			break;
		case NVARCHAR:
			bstmnt.setString(i, StringEscapeUtils.unescapeJava(value));
			break;
		case JSON:
			if (value != null) {
				extractJson(value, bstmnt, i, databaseName);
			}else {
				bstmnt.setNull(i, Types.NULL);
			}
			break;
		case TIME:
			if (value != null) {
				bstmnt.setTime(i, Time.valueOf(value));
			} else {
				bstmnt.setNull(i, Types.TIME);
			}
			break;
		case BOOLEAN:
			if (value != null) {
				Boolean flag = Boolean.valueOf(value);
				bstmnt.setBoolean(i, flag);
			} else {
				bstmnt.setNull(i, Types.BOOLEAN);
			}
			break;
		default:
			break;
		}
	}

	/**
	 * Method to extract JSON Value from the input request and set it to prepared
	 * statement based on the database names
	 * 
	 * @param value
	 * @param bstmnt
	 * @param i
	 * @param databaseName
	 * @throws SQLException
	 */
	public static void extractJson(String value, PreparedStatement bstmnt, int i, String databaseName)
			throws SQLException {
		if (databaseName.equals(POSTGRESQL)) {
			PGobject jsonObject = new PGobject();
			jsonObject.setType("json");
			jsonObject.setValue(value);
			bstmnt.setObject(i, jsonObject);
		} else if (databaseName.equals(ORACLE)) {
			OracleJsonFactory factory = new OracleJsonFactory();
			OracleJsonObject object = factory.createObject();
			JSONObject jsonObject = new JSONObject(value);
			Iterator<String> keys = jsonObject.keys();
			while (keys.hasNext()) {
				String jsonKeys = keys.next();
				object.put(jsonKeys, jsonObject.get(jsonKeys).toString());
			}
			bstmnt.setObject(i, object, OracleType.JSON);
		} else {
			bstmnt.setString(i, value);
		}
	}
	
	/**
	 * Method to extract JSON Value from the input request and set it to prepared
	 * statement based on the database names
	 * 
	 * @param value
	 * @param bstmnt
	 * @param i
	 * @param databaseName
	 * @throws SQLException
	 */
	public static void extractUnescapeJson(PreparedStatement pstmnt, int i, String databasename, JsonNode fieldValue)
			throws SQLException {
		if (databasename.equals(POSTGRESQL)) {
			PGobject jsonObject = new PGobject();
			jsonObject.setType("json");
			jsonObject.setValue(fieldValue.toString());
			pstmnt.setObject(i, jsonObject);
		} else if (databasename.equals(ORACLE)) {
			OracleJsonFactory factory = new OracleJsonFactory();
			OracleJsonObject object = factory.createObject();
			JSONObject jsonObject = new JSONObject(fieldValue.toString());
			Iterator<String> keys = jsonObject.keys();
			while (keys.hasNext()) {
				String jsonKeys = keys.next();
				object.put(jsonKeys, jsonObject.get(jsonKeys).toString());
			}
			pstmnt.setObject(i, object, OracleType.JSON);
		} else {
			pstmnt.setString(i, StringEscapeUtils.unescapeJava(fieldValue.toString()));
		}
	}

}
